version: "3.9"

services:
  postgres:
    image: postgres:13
    container_name: ny_taxi_pg   
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ny_taxi
    ports:
      - "5433:5432"              
    volumes:
      - ./ny_taxi_postgres_data:/var/lib/postgresql/data
      - ./sql:/sql               
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped
